<a href="https://colab.research.google.com/github/suryavanshi18/Pytorch_Learnings/blob/main/Basic_Models_in_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
class Model(nn.Module):
  def __init__(self):
    super().__init__()
    self.layer1=nn.Linear(128,32)
    self.layer2=nn.Linear(32,16)
    self.layer3=nn.Linear(16,1)
  def forward(self,features):
    x=self.layer1(features)
    x=self.layer2(x)
    x=self.layer3(x)
    return x

In [3]:
model=Model()
features=torch.rand((3,128))
#3 is the batch size and 128 is the number of features for input
#128 is fed in the layer1 in_features
#For outfeatures in layer1 we can define any number and after that we build the layer
model(features)
#Since batch size is 3 we would get 3 outputs

tensor([[-0.1481],
        [-0.0863],
        [-0.0757]], grad_fn=<AddmmBackward0>)

In [4]:
#Here we are implementing a linear regression model
x=torch.rand((3,10))
in_features=x.shape[1]
out_features=5
m=nn.Linear(in_features,out_features)

In [5]:
y=m(x)
#Behind the scenes
#y = x.matmul(m.weight.t()) + m.bias
print(y)
#Note that variable m would have weights and bias as the parameters
print(m.weight)
#The dimension of weight would be out_features,in_features
print(m.bias)
#The dimension of bias would be out_features

tensor([[-0.0286, -0.2675, -0.9084,  0.2820,  0.1281],
        [-0.0286, -0.4838, -0.5464,  0.3522,  0.1278],
        [-0.0281, -0.4795, -0.4652,  0.6217,  0.0554]],
       grad_fn=<AddmmBackward0>)
Parameter containing:
tensor([[-0.1109,  0.0564, -0.1142, -0.0596,  0.0852, -0.1523,  0.2055, -0.1890,
          0.2481,  0.0218],
        [ 0.0742, -0.0650, -0.0913, -0.0781,  0.2768,  0.0294,  0.1040, -0.2514,
          0.1815, -0.2111],
        [-0.1589, -0.1758, -0.0346, -0.3130, -0.1153, -0.0877, -0.1820, -0.2714,
         -0.1276,  0.1889],
        [ 0.0141,  0.1995,  0.2687, -0.2341,  0.2490, -0.1239,  0.0618, -0.0386,
         -0.3141,  0.2102],
        [ 0.1419,  0.2515, -0.1898, -0.1550,  0.0170,  0.0734, -0.0980, -0.2771,
         -0.1926,  0.2839]], requires_grad=True)
Parameter containing:
tensor([ 0.1926, -0.2347,  0.0652,  0.2463,  0.1092], requires_grad=True)


In [6]:
class LinearRegression(nn.Module):
  def __init__(self):
    super(LinearRegression,self).__init__()
    self.layer1=nn.Linear(1,1)
  def forward(self,x):
    y_pred=self.layer1(x)
    return y_pred

In [7]:
x=torch.rand((1,1))
print(x)
model=LinearRegression()
y=model(x)
print(y)

tensor([[0.9783]])
tensor([[-1.0475]], grad_fn=<AddmmBackward0>)


In [8]:
x=torch.rand((1,1))
x

tensor([[0.6812]])

<b>Assumptions for linear regression</b><br>
The relationship between the independent and dependent variables should be linear. <br>
No Multicolinaerity: If the predictor variables are correlated among themselves, then the data is said to have a multicollinearity problem. But why is this a problem? The answer to this question is that high collinearity means that the two variables vary very similarly and contain the same kind of information<br>
Homoscedasity is the term that states that the spread residuals which we are getting from the linear regression model should be homogeneous or equal spaces.<br>
This assumption ensures that you have equally distributed observations for the range of each predictor



In [9]:
#Autograd
#Automatic differentiation engine in pytorch
a=torch.tensor([5.],requires_grad=True)
b=torch.tensor([6.],requires_grad=True)

In [10]:
y=a**3+b**2

In [11]:
#calculating gradients
#dy/da->3*a**2->
#dy/db->2*b
#Using autograd we can do automatically

In [12]:
y.backward()

In [13]:
a.grad

tensor([75.])

In [14]:
b.grad

tensor([12.])

In [15]:
W=torch.randn(10,1,requires_grad=True)
b=torch.randn(1,requires_grad=True)

In [16]:
x=torch.rand(1,10)

In [17]:
y=torch.matmul(x,W)+b

In [18]:
loss=1-y

In [20]:
loss.backward()

In [22]:
W.grad

tensor([[-0.6927],
        [-0.8831],
        [-0.9220],
        [-0.7270],
        [-0.9824],
        [-0.5396],
        [-0.4486],
        [-0.0477],
        [-0.2235],
        [-0.6920]])

In [23]:
b.grad

tensor([-1.])

In [24]:
learning_rate=0.01
with torch.no_grad():#We use no grad so that grad for variables is not calculate again
  W=W-learning_rate*W.grad.data

In [25]:
W

tensor([[-0.1391],
        [-1.0786],
        [ 0.3194],
        [-0.4274],
        [ 0.4103],
        [ 0.9445],
        [-0.7255],
        [ 1.5818],
        [-0.6740],
        [-1.9844]])

In [26]:
with torch.no_grad():
  b=b-learning_rate*b.grad.data

In [27]:
b

tensor([-0.1013])

In [74]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn import metrics
import torch

In [49]:
#Custom Dataset for linear regression
class CustomDataset:
  def __init__(self,data,targets):
    self.data=data
    self.targets=targets
  def __len__(self):
    return self.data.shape[0]
  def __getitem__(self,index):
    currSample=self.data[index,:]
    currTarget=self.targets[index]
    return {
        "samples":torch.tensor(currSample,dtype=torch.float),
        "target":torch.tensor(currTarget,dtype=torch.long)
    }

In [50]:
data,targets=make_classification(n_samples=1000)

In [32]:
data.shape

(1000, 20)

In [33]:
targets.shape

(1000,)

In [51]:
custom_datasets=CustomDataset(data=data,targets=targets)

In [39]:
len(custom_datasets)

1000

In [53]:
custom_datasets[0]["samples"]

tensor([ 0.5168,  1.0521,  0.3937, -1.1096, -0.1974, -0.9935,  0.3359,  1.2228,
         0.4102,  0.3713,  0.4903, -0.3093,  0.1157, -0.1246, -0.1159, -1.7033,
         0.4199, -0.4288,  2.1212,  0.7183])

In [58]:
#Dataloader
#We need to load the data in batches to train our model
#batch size->how many samples per batch to load
#num_workers->how many subprocesses(cores) to use for data loading. 0->means data will be loaded in main process
#drop_last->if dataset is not divisible by batch size then we can set this to true
#train_loader is a generator
train_loader=torch.utils.data.DataLoader(custom_datasets,batch_size=4,num_workers=2)

In [62]:
for data in train_loader:
  print(data)
  print(data["samples"].shape)
  print(data["target"].shape)
  break

{'samples': tensor([[ 5.1676e-01,  1.0521e+00,  3.9372e-01, -1.1096e+00, -1.9742e-01,
         -9.9348e-01,  3.3588e-01,  1.2228e+00,  4.1022e-01,  3.7128e-01,
          4.9033e-01, -3.0926e-01,  1.1567e-01, -1.2461e-01, -1.1585e-01,
         -1.7033e+00,  4.1993e-01, -4.2885e-01,  2.1212e+00,  7.1825e-01],
        [-1.7541e+00,  1.5257e-01, -1.2827e+00, -1.0326e+00, -3.7459e-01,
         -2.9405e-01, -1.3067e-01,  2.7293e-01, -6.5734e-01,  2.7518e+00,
         -2.5912e+00, -2.0071e-01,  6.2650e-01,  1.1075e+00, -1.5948e+00,
         -3.7932e-01, -7.3896e-02,  2.2073e+00, -1.2723e+00, -1.1668e+00],
        [-4.7920e-01, -9.7815e-01, -8.5595e-01, -4.5432e-01,  2.1634e+00,
          5.7243e-01, -1.5957e-01, -1.9987e-02, -1.6884e-01, -7.0060e-01,
         -5.9811e-01, -7.7257e-01,  1.5815e-01,  2.2149e-01,  1.3980e-01,
          1.1005e-01,  2.1358e-01,  5.1399e-01,  1.0677e+00,  4.1008e-01],
        [-6.5755e-01, -1.7326e+00, -1.8578e-01,  7.6890e-01,  1.3393e+00,
          1.1344e+00,  

In [ ]:
# for epochs in range(10):
#   for data in train_loader:
#     #Do forward pass
#     x=data["samples"]
#     y=data["targets"]
#     outputs=model(x,y)
#     #loss
#     #loss backward


In [55]:
#train test split
#startify keeps the ratio of positive and negative samples in target variable same
tarin_data,test_data,train_targets,test_targets=train_test_split(data,targets,stratify=targets)

In [57]:
train_dataset=CustomDataset(tarin_data,train_targets)
test_dataset=CustomDataset(test_data,test_targets)

In [63]:
train_loader=torch.utils.data.DataLoader(train_dataset,batch_size=4,num_workers=2)
test_loader=torch.utils.data.DataLoader(test_dataset,batch_size=4,num_workers=2)

In [64]:
model=lambda x,w,b:torch.matmul(x,w)+b

In [65]:
tarin_data.shape

(750, 20)

In [66]:
test_data.shape

(250, 20)

In [70]:
W=torch.randn(20,1,requires_grad=True)
b=torch.randn(1,requires_grad=True)
learning_rate=0.001
for epoch in range(10):
  epoch_loss=0
  counter=0
  for data in train_loader:
    xtrain=data["samples"]
    ytrain=data["target"]
    output=model(xtrain,W,b)
    #view(-1) flattens the tensor
    #Using mean square error
    loss=torch.mean((ytrain.view(-1)-output.view(-1))**2)
    epoch_loss=epoch_loss+loss.item()
    #Calculate gradients
    loss.backward()
    with torch.no_grad():#Requires grad becomes false whatever you write inside it
      W=W-learning_rate*W.grad
      b=b-learning_rate*b.grad
    W.requires_grad_(True)
    b.requires_grad_(True)
    counter+=1
  print("Epoch:",epoch," Loss:",epoch_loss/counter)

Epoch: 0  Loss: 19.7356443788777
Epoch: 1  Loss: 6.080344937186926
Epoch: 2  Loss: 2.200814369947035
Epoch: 3  Loss: 0.9334232404907333
Epoch: 4  Loss: 0.4590252748135715
Epoch: 5  Loss: 0.26138423014669976
Epoch: 6  Loss: 0.1728114281047849
Epoch: 7  Loss: 0.13119471862793286
Epoch: 8  Loss: 0.11101175882318552
Epoch: 9  Loss: 0.10099751815358375


In [71]:
#Calculating metric
output=[]
label=[]
with torch.no_grad():
  for data in test_loader:
    xtest=data["samples"]
    ytest=data["target"]
    #W and b values are updated from training set
    op=model(xtest,W,b)
    label.append(ytest)
    output.append(op)

In [72]:
torch.cat(output).view(-1)

tensor([-1.7357e-01,  6.0895e-01,  2.9621e-02,  8.3146e-01,  1.3690e+00,
         6.5193e-01,  4.4165e-01,  1.0258e+00,  1.6780e-01, -1.1883e-01,
         2.3552e-01,  8.3548e-01,  5.5189e-01,  1.2748e+00, -3.3838e-03,
         1.7462e-01,  6.3678e-02,  1.1307e+00,  7.9388e-01, -3.9212e-01,
         2.7350e-01,  2.1527e-01,  8.8374e-01,  5.0823e-01,  6.8995e-01,
         9.3525e-02,  1.0282e+00,  3.4050e-01,  2.8947e-01,  5.3769e-01,
         1.2082e+00,  4.7015e-01, -2.2216e-01, -6.9085e-02,  2.1092e-01,
         1.0844e+00,  4.0619e-01, -5.0292e-02,  5.2326e-01,  5.3003e-01,
         1.1765e+00,  1.1850e+00,  3.1493e-01, -2.1505e-01,  1.9966e-01,
         2.5099e-01,  1.0766e-01,  1.3747e+00,  1.0393e+00,  8.9163e-01,
         7.7321e-01, -1.8958e-01,  8.1276e-01,  1.1491e+00,  7.5013e-01,
         3.7016e-01,  8.8186e-01, -1.9509e-01,  3.4284e-01,  8.2973e-01,
         9.7400e-01,  7.5238e-01,  6.7063e-01,  3.3359e-01,  6.6598e-01,
         6.0821e-01,  1.6733e-01,  4.0194e-02,  3.3

In [76]:
metrics.roc_auc_score(torch.cat(label).view(-1),torch.cat(output).view(-1))

0.951168