<a href="https://colab.research.google.com/github/suryavanshi18/Pytorch_Learnings/blob/main/Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
device="cuda" if torch.cuda.is_available() else "cpu"
my_tensor=torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device=device)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')

In [ ]:
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)

torch.float32
cuda:0
torch.Size([2, 3])


In [ ]:
x=torch.empty(size=(3,3))
x
#Returns a tensor filled with uninitialized data.

tensor([[-1.7726e-02,  3.1393e-41, -1.8759e-02],
        [ 3.1393e-41,  1.1210e-43,  0.0000e+00],
        [ 1.1210e-43,  0.0000e+00, -1.3801e+03]])

In [ ]:
#Zeros
tensor_zeros=torch.zeros((3,3))
print(tensor_zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
#Random
tensor_rand=torch.rand((3,3))
tensor_rand

tensor([[0.0339, 0.4509, 0.6733],
        [0.6463, 0.5658, 0.9280],
        [0.7044, 0.8727, 0.8576]])

In [ ]:
#Ones
tensor_ones=torch.ones((3,3))
print(tensor_ones)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
#Identity Matrix
tensor_eye=torch.eye(5,5)
print(tensor_eye)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [ ]:
#Arange
tensor_arange=torch.arange(start=0,end=3,step=0.5)
print(tensor_arange)

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])


In [ ]:
#Linespace
tensor_linespace=torch.linspace(start=0.1,end=2,steps=10)
tensor_linespace

tensor([0.1000, 0.3111, 0.5222, 0.7333, 0.9444, 1.1556, 1.3667, 1.5778, 1.7889,
        2.0000])

In [ ]:
#Normal Tensor
tensor_normal=torch.empty(size=(3,4)).normal_(mean=0,std=1)
tensor_normal

tensor([[-0.6417, -0.9556,  1.3379,  1.6353],
        [ 0.8567, -1.0174,  0.1074,  0.0916],
        [ 0.0484,  0.0576, -0.0425,  0.2518]])

In [ ]:
#Uniform Tensor
tensor_uniform=torch.empty(size=(3,4)).uniform_(4,6)
tensor_uniform

tensor([[5.7322, 5.7838, 4.1031, 4.6286],
        [4.2130, 5.1025, 4.6911, 4.3339],
        [5.2188, 4.8924, 5.4214, 5.6424]])

In [ ]:
tensor_arange=torch.arange(4)
print(tensor_arange.bool())

tensor([False,  True,  True,  True])


In [ ]:
import numpy as np
np_array=np.zeros((5,5))
tensor=torch.from_numpy(np_array)
np_array_back=tensor.numpy()

In [ ]:
#Add
x=torch.tensor([1,2,3])
y=torch.tensor([9,8,7])
z1=torch.empty(3)
torch.add(x,y,out=z1)


tensor([10., 10., 10.])

In [ ]:
z2=torch.add(x,y)
print(z2)

tensor([10, 10, 10])


In [ ]:
#Multiplication
x1=torch.rand((2,5))
x2=torch.rand((5,3))
x3=torch.mm(x1,x2)
print(x3)

tensor([[0.5468, 0.8738, 0.9627],
        [1.7922, 1.6776, 1.8380]])


In [ ]:
dot=torch.dot(x,y)
print(dot)

tensor(46)


In [ ]:
batch=30
n=10
m=20
p=30
tensor1=torch.rand((batch,n,m))
tensor2=torch.rand((batch,m,p))
#n,m matches m,p->n,p final dim
out_bmm=torch.bmm(tensor1,tensor2)
out_bmm

tensor([[[5.1304, 5.8017, 5.0474,  ..., 5.1143, 5.3425, 4.5885],
         [6.4246, 6.6289, 5.6186,  ..., 5.4594, 6.2092, 6.1835],
         [4.8559, 5.8464, 4.8927,  ..., 4.8041, 4.2654, 3.5779],
         ...,
         [4.8011, 5.5742, 4.8256,  ..., 3.8009, 4.4081, 4.3203],
         [4.2735, 5.7505, 4.6853,  ..., 4.0235, 4.3005, 4.6112],
         [5.8884, 6.0767, 4.8093,  ..., 5.3062, 4.7880, 4.9946]],

        [[3.6400, 4.4152, 4.3077,  ..., 3.6869, 4.4545, 4.4312],
         [4.5998, 4.7728, 3.8458,  ..., 5.0459, 4.6052, 4.7415],
         [4.6389, 6.1503, 6.0243,  ..., 4.9748, 5.3555, 5.8255],
         ...,
         [4.8706, 5.5529, 5.4544,  ..., 4.8024, 5.2684, 5.4740],
         [4.5231, 5.4201, 4.6092,  ..., 3.9174, 4.6261, 5.5280],
         [5.3986, 6.0843, 4.8438,  ..., 5.4757, 5.7669, 5.3299]],

        [[2.9895, 4.4752, 4.2776,  ..., 4.2128, 3.2156, 5.4141],
         [4.2118, 5.4581, 5.1160,  ..., 5.5303, 4.3354, 6.2674],
         [5.0833, 5.9103, 5.7432,  ..., 6.4196, 4.4131, 7.

In [ ]:
out_bmm.shape

torch.Size([30, 10, 30])

In [ ]:
#Broadcasting
x1=torch.rand((2,3))
x2=torch.rand((1,5))
sum_x_dim0=torch.sum(x1,dim=0)
sum_x_dim1=torch.sum(x1,dim=1)
print(sum_x_dim1)
print(sum_x_dim0)

tensor([1.9884, 2.1313])
tensor([1.8226, 0.8425, 1.4546])
